// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestServer.Models;

namespace animal_shelter.Migrations
{
    [DbContext(typeof(RestServerContext))]
    [Migration("20210719184843_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RestServer.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 15,
                            Available = true,
                            Name = "John",
                            Sex = "Male",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 2,
                            Age = 15,
                            Available = false,
                            Name = "Robb",
                            Sex = "Male",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 3,
                            Age = 11,
                            Available = true,
                            Name = "Sansa",
                            Sex = "Female",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 4,
                            Age = 7,
                            Available = true,
                            Name = "Bran",
                            Sex = "Male",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 5,
                            Age = 9,
                            Available = true,
                            Name = "Arya",
                            Sex = "Female",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 6,
                            Age = 3,
                            Available = false,
                            Name = "Rickon",
                            Sex = "Male",
                            Type = "cat"
                        },
                        new
                        {
                            Id = 7,
                            Age = 1,
                            Available = true,
                            Name = "Ghost",
                            Sex = "Male",
                            Type = "dog"
                        },
                        new
                        {
                            Id = 8,
                            Age = 1,
                            Available = false,
                            Name = "Grey Wind",
                            Sex = "Male",
                            Type = "dog"
                        },
                        new
                        {
                            Id = 9,
                            Age = 1,
                            Available = false,
                            Name = "Lady",
                            Sex = "Female",
                            Type = "dog"
                        },
                        new
                        {
                            Id = 10,
                            Age = 1,
                            Available = true,
                            Name = "Nymeria",
                            Sex = "Female",
                            Type = "dog"
                        },
                        new
                        {
                            Id = 11,
                            Age = 1,
                            Available = false,
                            Name = "Summer",
                            Sex = "Male",
                            Type = "dog"
                        },
                        new
                        {
                            Id = 12,
                            Age = 1,
                            Available = false,
                            Name = "Shaggy Dog",
                            Sex = "Male",
                            Type = "dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
